// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/charts/[charts].tsx";
import * as $1 from "./routes/charts/_middleware.ts";
import * as $2 from "./routes/docCharts/[charts].tsx";
import * as $3 from "./routes/documentation.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/samples.tsx";
import * as $$0 from "./islands/Button.tsx";
import * as $$1 from "./islands/ChartContainer.tsx";
import * as $$2 from "./islands/ChartDoc.tsx";
import * as $$3 from "./islands/ChartRedirect.tsx";
import * as $$4 from "./islands/Documentation.tsx";
import * as $$5 from "./islands/Header.tsx";
import * as $$6 from "./islands/NavBar.tsx";

const manifest = {
  routes: {
    "./routes/charts/[charts].tsx": $0,
    "./routes/charts/_middleware.ts": $1,
    "./routes/docCharts/[charts].tsx": $2,
    "./routes/documentation.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/samples.tsx": $5,
  },
  islands: {
    "./islands/Button.tsx": $$0,
    "./islands/ChartContainer.tsx": $$1,
    "./islands/ChartDoc.tsx": $$2,
    "./islands/ChartRedirect.tsx": $$3,
    "./islands/Documentation.tsx": $$4,
    "./islands/Header.tsx": $$5,
    "./islands/NavBar.tsx": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
