// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/charts/[charts].tsx";
import * as $1 from "./routes/charts/_middleware.ts";
import * as $2 from "./routes/charts/index.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/ChartContainer.tsx";
import * as $$1 from "./islands/ChartRedirect.tsx";
import * as $$2 from "./islands/Header.tsx";
import * as $$3 from "./islands/NavBar.tsx";

const manifest = {
  routes: {
    "./routes/charts/[charts].tsx": $0,
    "./routes/charts/_middleware.ts": $1,
    "./routes/charts/index.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/ChartContainer.tsx": $$0,
    "./islands/ChartRedirect.tsx": $$1,
    "./islands/Header.tsx": $$2,
    "./islands/NavBar.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
