// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/charts/[chart].tsx";
import * as $1 from "./routes/greet/[name].tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/samples.tsx";
import * as $$0 from "./islands/NavBar.tsx";

const manifest = {
  routes: {
    "./routes/charts/[chart].tsx": $0,
    "./routes/greet/[name].tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/samples.tsx": $3,
  },
  islands: {
    "./islands/NavBar.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
