export default [
  {
    name: "data",
    type: "{x: number, y: number}[]",
    defaultValue: "N/A",
    required: "Yes",
    description:
      "data used to render pie / donut chart. It is an array of objects that has corresponding x and y values as number to define the proportion and its labels.",
  },
  {
    name: ["paddingTop", "paddingLeft", "paddingRight", "paddingBottom"],
    type: "number",
    defaultValue: "50",
    required: "No",
    description: "add top, left, right, bottom padding to the chart",
  },
  {
    name: "width",
    type: "number",
    defaultValue: "500",
    required: "No",
    description: "set width size of the chart",
  },
  {
    name: "height",
    type: "number",
    defaultValue: "500",
    required: "No",
    description: "set height size of the chart",
  },
  {
    name: "colorRange",
    type: "string",
    defaultValue: [
      "#CED89E",
      "#F9F9C5",
      "#6CC4A1",
      "#AEDBCE",
      "#76BA99",
      "#D9F8C4",
      "#90C8AC",
    ],
    required: "No",
    description: "range of color used on the chart",
  },
  {
    name: "animation",
    type: "boolean",
    defaultValue: "true",
    required: "No",
    description: "animation for pie / donut chart",
  },
  {
    name: "animationDuration",
    type: "number",
    defaultValue: "120",
    required: "No",
    description: "time in ms each of the chart's slice to render",
  },
  {
    name: "addToolTip",
    type: "boolean",
    defaultValue: "true",
    required: "No",
    description: "add tool tip to the chart",
  },
  {
    name: "fontFamily",
    type: "string",
    defaultValue: "Verdana",
    required: "No",
    description: "font family for the text in chart",
  },
  {
    name: "addTitle",
    type: "boolean",
    defaultValue: "false",
    required: "No",
    description: "add title to the chart",
  },
  {
    name: "setTitle",
    type: "string",
    defaultValue: "TITLE",
    required: "No",
    description: "set title for the chart",
  },
  {
    name: "setTitleSize",
    type: "string",
    defaultValue: "1em",
    required: "No",
    description: "set font size for the chart's title",
  },
  {
    name: "setTitleColor",
    type: "string",
    defaultValue: "#277DA1",
    required: "No",
    description: "set color of the chart's title",
  },
];
