export default [
  {
    name: ["paddingTop", "paddingLeft", "paddingRight", "paddingBottom"],
    type: "number",
    defaultValue: "70",
    required: "No",
    description: "add top, left, right, bottom padding to the chart",
  },
  {
    name: "width",
    type: "number",
    defaultValue: "600",
    required: "No",
    description: "set width size of the chart",
  },
  {
    name: "height",
    type: "number",
    defaultValue: "600",
    required: "No",
    description: "set height size of the chart",
  },
  {
    name: "data",
    type: "{x: number, y: number}[]",
    defaultValue: "N/A",
    required: "Yes",
    description:
      "data used to render scatterplot chart. An array of objects that contains the x and y for each dot.",
  },
  {
    name: "dotColor",
    type: "string",
    defaultValue: "#BFE4A3",
    required: "No",
    description: "color of dot on chart",
  },
  {
    name: "dotHoverColor",
    type: "string",
    defaultValue: "#90BE6D",
    required: "No",
    description: "color of dot on chart upon hover",
  },
  {
    name: "dotSize",
    type: "string",
    defaultValue: "5",
    required: "No",
    description: "radius of each dot on chart",
  },
  {
    name: "addAxesLabel",
    type: "boolean",
    defaultValue: "false",
    required: "No",
    description: "add labels to the chart's axes",
  },
  {
    name: "xAxisLabel",
    type: "string",
    defaultValue: "x label",
    required: "No",
    description: "text to display for x axis label",
  },
  {
    name: "yAxisLabel",
    type: "string",
    defaultValue: "y label",
    required: "No",
    description: "text to display for y axis label",
  },
  {
    name: "axesColor",
    type: "string",
    defaultValue: "#4D908E",
    required: "No",
    description: "color for axes",
  },
  {
    name: "axesLabelColor",
    type: "string",
    defaultValue: "#277DA1",
    required: "No",
    description: "color for axes' labels",
  },
  {
    name: "animation",
    type: "boolean",
    defaultValue: "true",
    required: "No",
    description: "animation for scatterplot chart",
  },
  {
    name: "animationDuration",
    type: "number",
    defaultValue: "1200",
    required: "No",
    description: "time in ms for dots to move to its specified position",
  },
  {
    name: "addToolTip",
    type: "boolean",
    defaultValue: "true",
    required: "No",
    description: "add tool tip to the chart",
  },
  {
    name: "fontFamily",
    type: "string",
    defaultValue: "Verdana",
    required: "No",
    description: "font family for the text in chart",
  },
  {
    name: "addTitle",
    type: "boolean",
    defaultValue: "false",
    required: "No",
    description: "add title to the chart",
  },
  {
    name: "setTitle",
    type: "string",
    defaultValue: "TITLE",
    required: "No",
    description: "set title for the chart",
  },
  {
    name: "setTitleSize",
    type: "string",
    defaultValue: "1.5em",
    required: "No",
    description: "set font size for the chart's title",
  },
  {
    name: "setTitleColor",
    type: "string",
    defaultValue: "#277DA1",
    required: "No",
    description: "set color of the chart's title",
  },
];
